### PR TITLE
Modified run.sh to install just the required CRDs from pipeline repo

### PR DESCRIPTION
**Pull request by bnallapeta**
Note: Pipeline repo changes is made on the pipeline repo.

### CODE REVIEW

**Comment by guillaumerose** [comment]
I tried the current PR and I got:

```
HEAD is now at d2456ab9a Commenting out Informers and Listers for CRDs that are not necessary to run pipelines-as-a-service on kcp
+ cd pipeline
+ git apply ../../label.patch
error: patch failed: pkg/reconciler/taskrun/taskrun.go:697
error: pkg/reconciler/taskrun/taskrun.go: patch does not apply
+ jobs=($(jobs -p))
++ jobs -p
+ '[' -n '' ']'
+ true
```

Can you try to make it pass?

**Comment by bnallapeta** [comment]
> I tried the current PR and I got:
> 
> ```
> HEAD is now at d2456ab9a Commenting out Informers and Listers for CRDs that are not necessary to run pipelines-as-a-service on kcp
> + cd pipeline
> + git apply ../../label.patch
> error: patch failed: pkg/reconciler/taskrun/taskrun.go:697
> error: pkg/reconciler/taskrun/taskrun.go: patch does not apply
> + jobs=($(jobs -p))
> ++ jobs -p
> + '[' -n '' ']'
> + true
> ```
> 
> Can you try to make it pass?



@guillaumerose 

I have modified git clone to clone the specific branch used for this activity. It is going through now.

```
+ git clone git@github.com:bnallapeta/pipeline.git -b kcp-pipelines
Cloning into 'pipeline'...
remote: Enumerating objects: 65971, done.
remote: Counting objects: 100% (5294/5294), done.
remote: Compressing objects: 100% (2392/2392), done.
remote: Total 65971 (delta 2833), reused 4919 (delta 2661), pack-reused 60677
Receiving objects: 100% (65971/65971), 85.10 MiB | 8.80 MiB/s, done.
Resolving deltas: 100% (39708/39708), done.
+ cd ./pipeline
+ git checkout 2e43f1d5eee426480ddac09ce9803a19faa19cc7
Note: switching to '2e43f1d5eee426480ddac09ce9803a19faa19cc7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 2e43f1d5e Reverting changes applied due to patch files in run.sh
+ cd pipeline
+ git apply ../../label.patch
+ cd pipeline
+ git apply ../../pipeline-ff.patch
+ cd pipeline
+ git apply ../../remove-conversion.patch

```

```
+ kubectl get pods,taskruns,pipelineruns
NAME                                   READY   STATUS      RESTARTS   AGE
pod/custom-env-7x9wf-pod               0/1     Completed   0          2m
pod/test-pipelinerun-nssfs-task1-pod   0/3     Completed   0          2m

NAME                                              SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
taskrun.tekton.dev/custom-env-7x9wf               True        Succeeded   2m          63s
taskrun.tekton.dev/test-pipelinerun-nssfs-task1   True        Succeeded   2m          57s

NAME                                            SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
pipelinerun.tekton.dev/test-pipelinerun-nssfs   True        Succeeded   2m          57s

```

**Comment by guillaumerose** [comment]
Looks good! thanks.

Do you know if we can remove pipelineresource and run CRDs also?

**Comment by bnallapeta** [comment]
> Looks good! thanks.
> 
> Do you know if we can remove pipelineresource and run CRDs also?

No, it doesn't work. I did try removing pipelineresource but it has a lot of inter-dependencies within the code.

P.S. maybe there's a future plan to remove pipelineresource off tekton completely.
(https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md)

**Pull request merged**
