### PR TITLE
Shellcheck compliancy

### PR DESCRIPTION
**Pull request by Roming22**
This PR solves some (but not all) shellcheck issues.

### CODE REVIEW

**Comment by fgiloux** [comment]
@Roming22 have you tested every single changes? I remember that some "recommendations" were just plain breaking the code

**Comment by xinredhat** [comment]
maybe we can specify `--severity=warning`

**Comment by Roming22** [comment]
@fgiloux There was an issue with `local/kcp/start.sh` where I needed to convert a var into an array,  but otherwise I have the same behavior on this branch and main (with `local/kind/setup.sh` throwing `error: availableReplicas is not found` if I do not use `NO_ARGOCD=true`).

**Comment by fgiloux** [comment]
> @fgiloux There was an issue with `local/kcp/start.sh` where I needed to convert a var into an array, but otherwise I have the same behavior on this branch and main (with `local/kind/setup.sh` throwing `error: availableReplicas is not found` if I do not use `NO_ARGOCD=true`).

I tested it successfully. As discussed on chat you may have hit the issue described in the development readme: [too many open files](https://github.com/openshift-pipelines/pipelines-service/blob/main/DEVELOPMENT.md#troubleshooting)

**Review by bnallapeta — APPROVED** [review]
Ran ckcp/openshift_dev_setup.sh locally. LGTM.

**Pull request merged**
