### PR TITLE
Update kcp/README 

### PR DESCRIPTION
**Pull request by RAMESSESII2**
The new changes in `./kcp/README.md` allow users to be able to use "login.sh"

### CODE REVIEW

**Comment by RAMESSESII2** [comment]
@Roming22 please see if it's good to go.

**Comment by RAMESSESII2** [comment]
@Roming22 please see it's good to go.

**Comment by Roming22** [comment]
We should not reference the infra repository (an internal RH repository) in this repository. Please create/update the README.md in the infra repository if necessary.

**Comment by Roming22** [comment]
I see. That's my fault for forgetting to remove the reference to that script when I moved it to another repo. https://github.com/openshift-pipelines/pipelines-service/pull/60 should take care of it.
If you agree you can close this PR.

**Pull request closed without merging**
